### ISSUE TITLE
Browser blank page

### ISSUE THREAD

**Issue by toshibochan** [NorDroN/homebridge-wideq#20]
I pasted the link in the browser and logged in in my account but the browser showing just blank page after logging. Please help any idea what’s happening?

**Comment by toshibochan** [comment]
Are use iOS device in Mac but both showing blank page

**Comment by toshibochan** [comment]
loged in and copy the link and past in the terminal but give me error.

(node:90720) UnhandledPromiseRejectionWarning: Error: write EPROTO 4428101056:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1942:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:90720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:90720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by town3r** [comment]
Same.
Pretty sure this plugin is dead unless the dev is able to release a fix.

**Comment by town3r** [comment]
You could try the following:

sudo nano /etc/ssl/openssl.cnf 

and change MinProtocol to TLSv1.0. 

It was 1.2.

**Comment by toshibochan** [comment]
I was doing in the Mac and not work but I tried on the raspberry pi and work. But I have washing machine and dryer. Only one ON/OFF switch appears and do nothing.
