### ISSUE TITLE
wideq crashes after pasting the redirected URL

### ISSUE THREAD

**Issue by daciand** [NorDroN/homebridge-wideq#5]
Hi,
Currently I cannot pass forward the oauth part:

``pi@raspberrypi:~ $ sudo wideq auth -c RO -l ro-RO
Log in here: https://ro.m.lgaccount.com/login/sign_in?country=RO&language=ro-RO&svcCode=SVC202&authSvr=oauth2&client_id=LGAO221A02&division=ha&grant_type=password
Then paste the URL where the browser is redirected: https://ro.m.lgaccount.com/login/iabClose?access_token=***&refresh_token=***&oauth2_backend_url=https://gb.lgeapi.com/
(node:21872) UnhandledPromiseRejectionWarning: Error: write EPROTO 1991948752:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2150:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:21872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.``

I've replaced both tokens with "***" for security reasons.

**Comment by NorDroN** [comment]
Please, see #4
